# Generated by Django 5.2.10 on 2026-01-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('tipo_endereco', models.CharField(choices=[('USINA', 'Usina'), ('EMPRESA', 'Empresa'), ('UNIDADE_CONSUMIDORA', 'Unidade Consumidora')], default='UNIDADE_CONSUMIDORA', max_length=19, verbose_name='Tipo de endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('potencia_instalada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_instalacao', models.DateField()),
                ('tipo_status', models.CharField(choices=[('ATIVA', 'ativa'), ('INATIVA', 'inativa'), ('BLOQUEADA', 'bloqueada')], default='ATIVA', max_length=15, verbose_name='Tipo de status da usina')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usinas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usinas', to='contas.empresa')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usina', to='usinas.endereco')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usinas', to='contas.pessoa')),
            ],
        ),
    ]
