# Generated by Django 5.2.10 on 2026-01-30 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=120)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tensao', models.DecimalField(decimal_places=0, max_digits=8)),
                ('tipo_equipamento', models.CharField(choices=[('MODULO_FOTOVOLTAICO_MONOFACIAL', 'Módulo fotovoltaico Monofacial'), ('MODULO_FOTOVOLTAICO_BIFACIAL', 'Módulo fotovoltaico Bifacial'), ('INVERSOR_CONVENCIONAL', 'Inversor Convencional'), ('INVERSOR_MICRO', 'Inversor Micro')], max_length=40, verbose_name='Tipo do equipamento')),
            ],
            options={
                'unique_together': {('fabricante', 'tipo_equipamento', 'potencia', 'tensao')},
            },
        ),
        migrations.CreateModel(
            name='KitSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_solares', to='equipamentos.equipamento')),
            ],
        ),
    ]
