# Generated by Django 5.2.10 on 2026-01-30 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitsolar',
            name='usina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_solares', to='usinas.usina'),
        ),
    ]
