# Generated by Django 5.2.6 on 2026-02-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name = "Vendedor",
            fields = [
                ("id", models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = "ID")),
                ("nome_completo", models.CharField(max_length = 255)),
                ("cpf", models.CharField(max_length = 14)),
                ("email_contato", models.EmailField(blank = True, max_length = 254, null = True)),
                ("telefone", models.CharField(max_length = 14)),
                ("percentual_comissao", models.DecimalField(decimal_places = 2, default = 0, max_digits = 5)),
                ("tipo_comissao", models.CharField(choices = [("PERCENTUAL", "Percentual"), ("FIXA", "Fixa")], default = "PERCENTUAL", max_length = 20)),
                ("inicio_vigencia", models.DateField()),
                ("fim_vigencia", models.DateField(blank = True, null = True)),
                ("tipo_status", models.CharField(choices = [("ATIVO", "ativo"), ("INATIVO", "inativo")], default = "ATIVO", max_length = 10, verbose_name = "Status do vendedor")),
                ("contrato_ativo", models.BooleanField(default = False)),
                ("comissionamento_pendente", models.BooleanField(default = False)),
                ("data_criacao", models.DateTimeField(auto_now_add = True)),
                ("data_atualizacao", models.DateTimeField(auto_now = True)),
                ("criado_por", models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.SET_NULL, related_name = "vendedores_criados", to = settings.AUTH_USER_MODEL)),
                ("empresa", models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, related_name = "vendedores", to = "contas.empresa")),
            ],
        ),
        migrations.AddConstraint(
            model_name = "vendedor",
            constraint = models.UniqueConstraint(fields = ("empresa", "cpf"), name = "unique_vendedor_cpf_empresa"),
        ),
    ]
